spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

flyway:
  check-location: true
  enabled: true
  locations: classpath:db/migration
server:
  port: 8080
  context-path: /transporthub

banner:
  location: classpath:banner.txt
logging:
  level:
    root: WARN

