spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  session:
    store-type: redis

  redis:
    host: localhost
    password:
    port: 32768

flyway:
  check-location: true
  enabled: true
  locations: classpath:db/migration
server:
  port: 8080
  context-path: /transporthub
